hw1
steshabolk/link-tracker pull request #1
Opened 2024-02-13 16:28 UTC by steshabolk

2024-02-18 15:31 UTC, SHvatov requested changes
@steshabolk привет! Меня зовут Сергей, и в этом семестре я буду проверять твои работы :) Если будут какие-то вопросы, можешь их смело задавать мне. Еще я создал небольшую группу в телеге для всяких анонсов, чисто для тех, кто ~~в теме~~ в моей группе. 

Оставил пару комментариев, посмотри их, пожалуйста.

2024-02-18 15:31 UTC, SHvatov commented on bot/pom.xml
> +        <!-- Emoji -->
:)

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/GlobalExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
Данный хэндлер будет применен только к запросами к сервису, то есть в данном кейсе он не особо применим.

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/enums/CommandType.java
> +    CommandType(String command, String description) {
Советую посмотреть в сторону использования lombok. В данном случае можно было бы заюзать @Getter, @RequiredArgsConstructor и сэкономить 15 строк рукописного кода :)

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/enums/CommandType.java
> +    CommandType(String command, String description) {
аналогично в других местах

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/enums/LinkType.java
> +    private final String domain;
Не хватает пустой строки. У тебя в проекте подключен код-стайл?

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/LinkHandler.java
> +public interface LinkHandler {
Точно ли нужен интерфейс? Предполагается наличие множества реализаций данного интерфейса?

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/LinkHandlerImpl.java
> +    private final String urlPattern = "^(http(s)?)://(www\\.)?[a-zA-Z\\d@:%._~=#&?/+-]+$";
Все эти константы стоит сделать статиками

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/LinkHandlerImpl.java
> +        List<LinkType> linkType = domains.stream().filter(domain -> domain.getDomain().equals(uri.getHost())).toList();
Советую придерживаться правила - новая точка -> новая строка. Так гораздо легче читать.

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/LinkHandlerImpl.java
> +    public SendMessage handleLink(Update update, BiConsumer<Long, LinkDto> linkOperation, String successReply) {
Новый публичный метод, которого нет в интерфейсе. Легко потерять, сложно найти.

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/LinkHandlerImpl.java
> +    public SendMessage handleLink(Update update, BiConsumer<Long, LinkDto> linkOperation, String successReply) {
А, получается метод `parseLink` стоит сделать приватным, ведь он нужен только для этого метода. А этот - вынести в интерфейс (или отказаться от интерфейса). Можешь, пожалуйста, пояснить мотивацию такого решения?)

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/LinkHandlerImpl.java
> +    public SendMessage handleLink(Update update, BiConsumer<Long, LinkDto> linkOperation, String successReply) {
И честно говоря, выглядит так, будто LinkHandler делает уж слишком много, что нарушает Single Responsibility. Он и парсит ссылку, и прихранивает ее в локал сторидже, и формирует ответ пользаку.

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/MessageHandler.java
> +    List<Command> commands();
Зачем нужен этот метод, кроме как для тестов?

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/MessageHandler.java
> +    List<Command> commands();
И снова вопрос про необходимость интерфейсов.

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/MessageHandlerImpl.java
> +    private final String unknownCommandReply =
статика

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/MessageHandlerImpl.java
> +        Long chatId = null;
```java 
var chatId = Optional.ofNullable(update.message())
            .filter(it -> StringUtils.hasText(it.text()))
            .map(Message::chat)
            .map(Chat::id)
            .orElse(null);
        if (chatId == null) {
            log.warn("error processing update: chat id is null");
            return null;
        }
        var command = commands.stream()
            .filter(cmd -> cmd.isTriggered(update))
            .findFirst();
        return command.map(it -> it.handle(update))
            .orElseGet(() -> sender.getSendMessage(chatId, unknownCommandReply));
```

Не забывай про optinal'ы и старайся придерживаться fail-fast approach - завершать метод как можно скорее. Так код становится чуть более легким в восприятии, потому что не нужно держать в голове `а что если?`

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/listener/BotListenerImpl.java
> +        menu = new SetMyCommands(
`Arrays.stream(CommandType.values())`. Старайся избегать таких явных перечислений, потому что можно легко забыть добавить сюда новое значение.

2024-02-18 15:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/sender/BotSender.java
> +public class BotSender {
Название немного вводит в заблуждение - я сначала думал, что класс про отправку, а он про формирование ответного сообщения. Я бы вообще его сделал утильным классом со статик методами.

2024-02-18 21:25 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/handler/LinkHandlerImpl.java
> +    public SendMessage handleLink(Update update, BiConsumer<Long, LinkDto> linkOperation, String successReply) {
интерфейс тут лишний, да. в LinkHandler предполагалось вынести обработку ссылки при командах добавления и удаления, т.к. различие только в вызове методов из scrapperService
если вынести парсинг ссылки в отдельный класс и оставить только метод handleLink, будет нормально?

2024-02-18 21:25 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/configuration/GlobalExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
т.е. можно класс GlobalExceptionHandler просто убрать?

2024-02-22 01:39 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/enums/CommandType.java
> +    CommandType(String command, String description) {
добавила аннотации

2024-02-22 01:44 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/handler/LinkHandler.java
> +public interface LinkHandler {
убрала этот интерфейс

2024-02-22 01:52 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/handler/MessageHandler.java
> +    List<Command> commands();
этот интерфейс тоже убрала

2024-02-22 01:54 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/sender/BotSender.java
> +public class BotSender {
перенесла в util

2024-02-22 02:04 UTC, steshabolk commented
исправила код по замечаниям

2024-02-25 17:06 UTC, SHvatov approved these changes
@steshabolk 👍, можно мержить.

2024-02-25 20:22 UTC, merged