hw3
steshabolk/link-tracker pull request #3
Opened 2024-03-03 05:48 UTC by steshabolk

команды:
- добавление ссылок
- получение списка
- удаление ссылки

![tg-command](https://github.com/steshabolk/link-tracker/assets/110855519/27af7c3e-a721-4e48-9cb3-ca3f84e975ef)
bot:
![bot-command](https://github.com/steshabolk/link-tracker/assets/110855519/ad3a7676-62f4-43d7-86ff-731493f0673e)
scrapper:
![scrapper-command](https://github.com/steshabolk/link-tracker/assets/110855519/11a32f73-9594-4c8a-a776-95fcca3e86cd)

обработка ошибок:
- невалидные ссылки
- повторное добавление
- удаление неотслеживаемой ссылки

![tg-error](https://github.com/steshabolk/link-tracker/assets/110855519/0a32affc-88a0-470b-a003-2aab2def869d)
![logs-error](https://github.com/steshabolk/link-tracker/assets/110855519/6ba2b4e3-b37c-48e7-88f6-e2c8069b6c93)

2024-03-05 19:46 UTC, SHvatov requested changes
@steshabolk буду честен - пристально просмотрел только половину всех изменений - уж больно их много :) Вообще хотел бы предложить следующее - рефакторинг это хорошо, но давай делить МРы на инфровые и бизнесовые. 

Бизнесовые - это те, что привносят что-то новое и имеют практическую ценность - то есть реализация ДЗ. 

Инфровые - это те, что нужны в первую очередь тебе, чтобы упростить дальнейшую реализацию. То есть, рефакторинг. 

И те, и те МРы я буду смотреть, просто беря в приоритете МРы из первой категории. Так и тебе, и мне будет гораздо легче отслеживать и продумывать эти самые изменения.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/ApplicationConfig.java
> +    public record ScrapperClient(@NotNull String api) {
`ScrapperClientConfig`, а то в чем разница с отдельно живущим `ScrapperClient` будет сложно понять. Даи целый объект под это заводить выглядит немного избыточным.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/ClientConfig.java
> +    private static final int TIMEOUT = 2000;
Стоит добавить единицы измерения в название, а то непонятно.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/enums/BotReply.java
> +    HELP_COMMAND(String.format("%s select one of the available commands:\n%s", Emoji.INFO.getMarkdown(),
Я бы разделил команды пустыми строками для удобочитаемости.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/enums/LinkType.java
> +    public boolean isSupportedSource(String url) {
Перечисление планомерно перерастает в компонент с собственной логикой, что не очень хорошо. Причем оба метода теперь не про определение типа ресурса (ГитХаб или Стэк), а про проверку и отображение ссылок. Может имеет смысл это утащить в полноценный комонент? И теперь логика стала еще сложнее для восприятия. Просто чтобы проерить себя - попробуй добавить новую команду. Что для этого понадобится, сколько изменений потребуется? А теперь то же самое, но с ресурсом)

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/enums/StackoverflowRegex.java
> +    QUESTION("/questions/(?<id>[\\d]+)");
А был бы это полноценный компонент / сервис, в него можно было бы запихнуть все это через проперти. И в итоге, вместо того, чтобы менять сервис, добавлять новые значения енама, достаточно было бы докинуть новые проперти в конфиг.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/LinkHandler.java
>              log.debug("error processing link={}", message);
С уровнем дебаг легко потерять ошибку.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/LinkHandler.java
> +            link = LinkParser.parseLink(message);
Не нравится мне такое разделение объявления и инициализации. Лучше так:

```java
      try {
            var link = LinkParser.parseLink(message);
            linkOperation.accept(chatId, link);
            return BotSendMessage.getSendMessage(chatId, operationReply);
        } catch (RuntimeException ex) {
            log.debug("error processing link={}", message);
            return BotSendMessage.getSendMessage(chatId, ex.getMessage());
        }
```

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/MessageHandler.java
> +    private final ObjectMapper mapper = new ObjectMapper();
Лучше заинжектить `objectMapper`, который предоставляет Spring. И вообще, на будущее - нужен объект -  объяви его бином и инжекти, а не создавай внутри компонента.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/MessageHandler.java
> +                chatId -> {
Давай разделим на три метода - получение мембера, обработка в случае существования, обработка в противном случае.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/MessageHandler.java
> +        if (ex instanceof WebClientResponseException clientExc
Сложная обработка, возможно она будет дублироваться, и я не уверен, что она должна быть в этом сервисе.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/MessageHandler.java
> +            case CHAT_NOT_FOUND -> BotReply.CHAT_NOT_FOUND.getReply();
Хороший пример нарушения Open/Closed принципа. Тут либо добавить в `BotReply` код ответа и маппить по нему, либо нужно еще подумать.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/BotService.java
> +                SendResponse botResponse = botListener.execute(BotSendMessage.getSendMessage(chatId, updateResponse));
Такое тоже стоит выносить в отдельный метод. Советую придерживаться правила - методы относительно небольшие, делают что-то одно, чем ниже по коду, тем атомарнее и конкретнее они становятся. Часто смотря чисто на код сложно понять, что он делает в реальности, а метод выступает в роли некоторого краткого описания, благодаря которому все становится гораздо проще для восприятия.

2024-03-05 19:46 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/telegram/command/ListCommand.java
> +            .map(e -> String.format("%s *%s*\n", Emoji.LINK.getMarkdown(), e.getKey().get())
Кол-во точек на квадратный пиксель моего экрана зашкаливает 😃

2024-03-05 19:46 UTC, SHvatov commented on scrapper/src/main/java/edu/java/configuration/GlobalExceptionHandler.java
> +    @ExceptionHandler(ApiException.class)
Такое чувство, будто в ApiException можно сразу хранить и создавать `ApiErrorResponse` - все нужное для этого там есть.

2024-03-05 19:46 UTC, SHvatov commented on scrapper/src/main/java/edu/java/util/Messages.java
> +public class Messages {
1. Название стоит конкретизировать, не просто же так в спринге класс называется `MessageSource`)
2. За поддержку локализации и чтения сообщений из отдельного файла - респект 👍

2024-03-11 05:05 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/enums/StackoverflowRegex.java
> +    QUESTION("/questions/(?<id>[\\d]+)");
попробовала вынести в отдельный компонент и заменить на использование проперти. не уверена, стало ли так попроще

2024-03-11 05:24 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/handler/LinkHandler.java
> +            link = LinkParser.parseLink(message);
так получается, из-за того что в catch должны отлавливаться только исключение от LinkParser, если в боте вводится невалидная ссылка. там еще в сonsumer-e передается метод добавить / удалить для скраппера, у которого в ответе может быть ошибки, и они должны обработаться в другом месте

2024-03-11 05:34 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/handler/MessageHandler.java
> +            case CHAT_NOT_FOUND -> BotReply.CHAT_NOT_FOUND.getReply();
отделила обработку от этого компонента, сделала маппинг через BotReply

2024-03-11 05:36 UTC, steshabolk commented on bot/src/main/java/edu/java/bot/telegram/command/ListCommand.java
> +            .map(e -> String.format("%s *%s*\n", Emoji.LINK.getMarkdown(), e.getKey().get())
разбила обработку на части

2024-03-11 05:54 UTC, steshabolk commented on scrapper/src/main/java/edu/java/configuration/GlobalExceptionHandler.java
> +    @ExceptionHandler(ApiException.class)
там еще нужно достать сообщение из пропертис, добавить description. и так сразу видно для всех исключений что и как в ответах отдается

2024-03-16 15:47 UTC, SHvatov approved these changes
@steshabolk 🆗, 🚀

2024-03-16 20:53 UTC, merged