hw5
steshabolk/link-tracker pull request #5
Opened 2024-03-16 22:53 UTC by steshabolk

2024-03-24 15:18 UTC, SHvatov requested changes
@steshabolk 👍, оставил пару комментариев, глянь их, пожалуйста.

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/entity/Chat.java
> +@EqualsAndHashCode(exclude = {"links"})
На будущее, когда будешь работать с гибером, имей в виду - https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/repository/ChatLinkRepository.java
> +    boolean isLinkAddedToChat(Chat chat, Link link);
Скажу честно, такие JPA-шные запросы писать будет сложновато.

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/repository/ChatRepository.java
> +    Chat findByChatId(Long chatId);
`findById` - классическое название для таких методов.

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcChatLinkRepository.java
> +        return Optional.ofNullable(jdbcTemplate.queryForObject(
А зачем тут в Optional оборачивать?

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcChatRepository.java
> +        return chats.stream()
1. Лучше уж клиенту отдавать Optional, чтобы он сам решал, чо с ним делать
2. У jdbcTemplate есть queryForStream
3. А норм, что ты просто берешь первый попавшийся? Может ошибку кидать, если объектов больше 1?

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +    private static final ResultSetExtractor<List<Link>> LINKS_WITH_CHATS_RESULT_SET_EXTRACTOR = rs -> {
Я бы вынес это в отдельную сущность

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +    private static final ResultSetExtractor<List<Link>> LINKS_WITH_CHATS_RESULT_SET_EXTRACTOR = rs -> {
Особенно с учетом того, что дело одним методом не ограничивается и нужны вспомогательные (mapChatFromResultSet, etc)

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/service/ChatService.java
> +public interface ChatService {
зочем....

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/service/LinkUpdaterService.java
> +    private static final Integer BATCH_SIZE = 50;
разделяй константы и обычные поля. первые стоит держать в самом верху

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
Плохое решение. Лучше бы сделать твой репозиторий абстрактным, и дальше в сервисе под капотом решать, использовать JDCB или JPA. А так у тебя будет отдельный новый репозиторий, и новый сервис, который, КМК, будет идентичен этому. Ну и нейминг плохой, потому что зачем мне, как пользователю твоего сервиса, знать, что там используется под капотом. Мне бы главное, чтобы работало.

2024-03-24 15:18 UTC, SHvatov commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +    @Transactional(readOnly = true)
а зачем? [про то, что это дает](https://stackoverflow.com/questions/1614139/spring-transactional-read-only-propagation)

2024-03-25 03:15 UTC, steshabolk commented on scrapper/src/main/java/edu/java/repository/ChatRepository.java
> +    Chat findByChatId(Long chatId);
ну это не id, который primary key, а chat_id, который приходит от тг

2024-03-25 03:18 UTC, steshabolk commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcChatLinkRepository.java
> +        return Optional.ofNullable(jdbcTemplate.queryForObject(
если оставлять без optional, то идея подсвечивает предупреждение npe, не хочется так оставлять
![01](https://github.com/steshabolk/link-tracker/assets/110855519/0a7fe76f-8f85-4fdb-9182-3203a72a2fdc)

2024-03-25 03:31 UTC, steshabolk commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcChatRepository.java
> +        return chats.stream()
тут может быть либо 1, либо вообще не быть, т.к. у chatId - unique. нужно ли добавлять ошибку ради ошибки? в примерах, которые мне попадались, либо так, либо через queryForObject, но там, как я поняла, нужно отлавливать EmptyResultDataAccessException если нет такого id. и вернуть optional, да

2024-03-25 04:31 UTC, steshabolk commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
да, ты буквально пересказал то, что и требуется сделать в этих наших дз)) реализовать имплементации сервисов и репозиториев и создавать нужные бины в зависимости от property jdbc/jpa. а где нужен сервис, используется интерфейс Chat-/LinkService. ты предлагаешь создать один сервис на всех и менять только репозитории? как быть с ChatLinkRepository в jpa? вариант с jpa есть в следующем дз, сервис не прямо 1 в 1

2024-03-26 05:21 UTC, SHvatov commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
> ты предлагаешь создать один сервис на всех и менять только репозитории

Все так. Скажу честно, мне не видны ваши следующие домашние задания, но я не понимаю, **как одни и те же сервисы, использующиеся в одних и тех же местах**, могут иметь различные интерфейсы и переключаться по проперте.

2024-03-26 05:22 UTC, SHvatov commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
Если считаешь, что текущее разделение - ОК, то давай оставим, и просто в рамках следующей ДЗ посмотрим, на сколько же сильно там изменится интерфейс (и почему).

2024-03-26 17:11 UTC, steshabolk commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
хорошо, давай ты в 6 дз проверишь что там с jpa и как это все можно сделать лучше

2024-03-26 18:45 UTC, SHvatov commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
ну давай

2024-03-27 13:00 UTC, SHvatov commented on scrapper/src/main/java/edu/java/repository/ChatRepository.java
> +    Chat findByChatId(Long chatId);
Очень странно тогда получается - в **Chat**Repository ты ищешь **Chat** по **chat_id**, и это, при этом, не ПК. Страшно представить тогда, что у тебя является реальным ИД сущности...

2024-03-27 13:02 UTC, SHvatov approved these changes
@steshabolk ок, остался вопрос про ИД чата, а так можно мержить.

2024-03-27 22:22 UTC, steshabolk commented on scrapper/src/main/java/edu/java/repository/ChatRepository.java
> +    Chat findByChatId(Long chatId);
https://github.com/steshabolk/link-tracker/blob/2443ac1b15ad9dd868bc08b329601833b4307655/migrations/scripts/1.0-create-chats-table.sql#L7-L11

пк - обычный генерируемый id, chat_id - тот id чата, что передается от тг. не уверена, насколько это критично менять схему, чтобы телеграмовский чат и был пк

2024-04-01 00:02 UTC, merged